### ISSUE TITLE
CI is failing on master

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/grpc-gcp-node#85]
I have a PR over in #84, and the system tests are failing with this stack:

```
Uncaught AssertionError [ERR_ASSERTION]: ifError got unwanted exception: 7 PERMISSION_DENIED: Caller is missing IAM permission spanner.sessions.create on resource projects/grpc-gcp/instances/sample/databases/benchmark.
      at Object.client.createSession [as callback] (test/integration/spanner_test.js:360:20)
      at Object.onReceiveStatus (node_modules/@grpc/grpc-js/build/src/client.js:176:36)
      at Object.callErrorFromStatus (node_modules/@grpc/grpc-js/build/src/call.js:31:26)
      at Object.onReceiveStatus (node_modules/@grpc/grpc-js/build/src/client.js:176:52)
      at listener.onReceiveStatus (node_modules/@grpc/grpc-js/build/src/call-stream.js:65:35)
      at Object.onReceiveStatus (build/src/index.js:73:29)
      at InterceptingListenerImpl.onReceiveStatus (node_modules/@grpc/grpc-js/build/src/call-stream.js:60:23)
      at Object.onReceiveStatus (node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
      at Object.onReceiveStatus (node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
      at process.nextTick (node_modules/@grpc/grpc-js/build/src/call-stream.js:130:78)
      at process._tickCallback (internal/process/next_tick.js:61:11)
```

Looks like a backend issue with the GCP project?

**Comment by stanley-cheung** [comment]
CI seems to be passing recently on PRs.

**Comment by stanley-cheung** [comment]
This is still an issue - see PR #99. It was masked by the fact that the "ci/kokoro: System test" PR test is not run for every PR. 

Looks like the last time this works was 2020/07/07. We should try to figure this out.
